### PR TITLE
Customer resource now exposed in API root document

### PR DESCRIPTION
**Pull request by mrozenbaum**
## 1. TITLE:
Created Customer Class to expose customer data.

## 2. STATUS:
complete

## 3. MIGRATIONS:
***YES*** (has been migrated) *or* ***NO*** (has not been migrated)

YES

## 4. DESCRIPTION:
***Rationale(reason behind updated changes)***
 Customer resource required to exposed in API root document
***Expected behavior of changes***

Customer resource required to exposed in API root document. working as expected.

## 6. FILES CHANGED:

settings.py
views.py
models.py
.gitignore
serializers.py
urls.py

## 7. STEPS TO RUN PROJECT:
python make migrations
run migrations
 python manage.py runserver

    
## 8. TESTING THE CODE:
N/A
***Name of test***

***Fail/ Pass***

***Description***

***How to run in command line***

### CODE REVIEW

**Comment by sarawithad** [comment]
Ran locally and customer shows up. Great job!

**Comment by Deanomatic** [comment]
I pulled down and ran the server. Everything works as expected.

**Comment by briwyatt** [comment]
this is working for me

**Comment by briwyatt** [comment]
:shipit:

**Comment by harryepstein** [comment]
It works! 🦑

**Pull request merged**
