### PR TITLE
Working master with all dummy data exposed

### PR DESCRIPTION
**Pull request by sarawithad**
## 1. TITLE:
Working master with all dummy data exposed

## 2. STATUS:
Ready to merge

## 3. MIGRATIONS:
***YES***

## 4. DESCRIPTION:
error in order.json needed to be fixed 

## 5. RELATED TICKETS:
#52 

## 6. FILES CHANGED:
order.json

## 7. STEPS TO RUN PROJECT:

```git checkout dt-master-test-2```

python manage.py loaddata department
python manage.py loaddata trainingProgram 
python manage.py loaddata computer       
python manage.py loaddata productType    
python manage.py loaddata customer   
python manage.py loaddata paymentType
python manage.py loaddata employee   
python manage.py loaddata product 
python manage.py loaddata order  

python manage.py createsuperuser
python manage.py runserver

### CODE REVIEW

**Comment by Deanomatic** [comment]
Everything works!!! The final product is ready 🎆

**Comment by mrozenbaum** [comment]
Looks good, great job! i approve to merge to master.

**Comment by Deanomatic** [comment]
⚔️

**Comment by briwyatt** [comment]
100 % working :shipit:

**Pull request merged**
