### PR TITLE
Created Product and Product Type dummy JSON data for testing database

### PR DESCRIPTION
**Pull request by sarawithad**
## 1. TITLE:
Filled in Product and Product Type JSON data for testing database

## 2. STATUS:
Complete, ready to merge

## 3. MIGRATIONS:
NO not necessary

## 4. DESCRIPTION:
Needed Product and Product Type dummy data for testing database.
Product and Product Type data should show up in database.

## 5. RELATED TICKETS:
#52 

## 6. FILES CHANGED:
product.JSON
productType.JSON

## 7. STEPS TO RUN PROJECT:

to load product type data: python manage.py loaddata productType

to load product data: python manage.py loaddata product 
^^(will NOT run until you load productType data)

to see data on API root:
python manage.py runserver

### CODE REVIEW

**Comment by mrozenbaum** [comment]
looks good! I think we can merge to master, we need to make sure that it works with all the other data correctly. in order to do that, we need to merge.

**Comment by Deanomatic** [comment]
After loading it in the right order it's all good to go!

**Comment by briwyatt** [comment]
working for me!!

**Comment by briwyatt** [comment]
:shipit:

**Pull request merged**
